// stdlib
#include <assert.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>
// system
#include <fcntl.h>
#include <poll.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netinet/ip.h>
// C++
#include <vector>

// Simple logging helper to stderr
static void msg(const char *msg) {
    fprintf(stderr, "%s\n", msg);
}

// Log an error message together with the current errno
static void msg_errno(const char *msg) {
    fprintf(stderr, "[errno:%d] %s\n", errno, msg);
}

// Fatal error helper: prints message and aborts the process
static void die(const char *msg) {
    int err { errno };
    fprintf(stderr, "[%d] %s\n", err, msg);   
    abort();
}

// Set the file descriptor `fd` to non-blocking mode.
// Uses fcntl to read and update the descriptor flags and aborts on unexpected errors.
static void fd_set_nb(int fd) {
    errno = 0;
    int flags { fcntl(fd, F_GETFL, 0) };
    if (errno) {
        die("fcntl error");
        return;
    }

    flags |= O_NONBLOCK;

    errno = 0;
    static_cast<void>(fcntl(fd, F_SETFL, flags));
    if (errno) {
        die("fcntl error");
    }
}

// Maximum allowed message size (32 MiB). Requests larger than this are rejected.
const size_t k_max_msg = 32 << 20;

// Representation of a single client connection
// - `fd` is the socket descriptor
// - `want_read`/`want_write` control what events we register into poll
// - `incoming` holds raw bytes received but not yet processed
// - `outgoing` holds bytes waiting to be written to the socket
struct Conn {
    int fd { -1 };
    // application's intentions for the event loop
    bool want_read { false }; 
    bool want_write { false };
    bool want_close { false };
    // buffered input and output
    std::vector<uint8_t> incoming; // data to be parsed by the application
    std::vector<uint8_t> outgoing; // responses generated by the application
};

// append to the back
static void buf_append(std::vector<uint8_t> &buf, const uint8_t *data, size_t len) {
    buf.insert(buf.end(), data, data + len);
}

// remove from the front
static void buf_consume(std::vector<uint8_t> &buf, size_t n) {
    buf.erase(buf.begin(), buf.begin() + n);
}

// Try to parse and handle a single framed request from `conn->incoming`.
// The protocol: 4-byte little-endian length prefix followed by `len` bytes of payload.
// If a full message is available, an echo response is appended to `conn->outgoing`.
// Returns true when a request was processed (so caller can loop and parse more).
static bool try_one_request(Conn *conn) {
    // Need at least 4 bytes for the length prefix
    if (conn->incoming.size() < 4) {
        return false;
    }

    uint32_t len { 0 };
    memcpy(&len, conn->incoming.data(), 4);

    // Reject overly large messages
    if (len > k_max_msg) {
        msg("too long");
        conn->want_close = true;
        return false;
    }

    // Wait until the full payload is available
    if (4 + len > conn->incoming.size()) {
        return false;
    }

    const uint8_t *request { &conn->incoming[4] };

    // echo response 
    buf_append(conn->outgoing, reinterpret_cast<const uint8_t *>(&len), 4);
    buf_append(conn->outgoing, request, len);

    // Remove the processed message from the incoming buffer
    buf_consume(conn->incoming, 4 + len);

    return true;
}

// Accept a new client connection on listening socket `fd`.
// Sets the returned connection socket to non-blocking mode and creates a Conn object.
static Conn *handle_accept(int fd) {
    // accept
    struct sockaddr_in client_addr { {} };
    socklen_t addrlen { sizeof(client_addr) };
    int connfd = accept(fd, reinterpret_cast<struct sockaddr *>(&client_addr), &addrlen);
    if (connfd < 0) {
        msg_errno("accept() error");
        return NULL;
    }

    // Print client address for debugging
    uint32_t ip { client_addr.sin_addr.s_addr };
    fprintf(stderr, "new client from %u.%u.%u.%u:%u\n",
        ip & 255, (ip >> 8) & 255, (ip >> 16) & 255, ip >> 24,
        ntohs(client_addr.sin_port)
    );

    // set the new connection fd to nonblocking mode
    fd_set_nb(connfd);

    // create a struct Conn
    Conn *conn { new Conn() };
    conn->fd = connfd;
    conn->want_read = true; // read 1st request
    return conn;
}

// Try to write pending bytes in `conn->outgoing` to the socket.
// On partial write we consume that many bytes; on EAGAIN we simply return and wait for POLLOUT.
static void handle_write(Conn *conn) {
    assert(conn->outgoing.size() > 0);
    ssize_t rv { write(conn->fd, conn->outgoing.data(), conn->outgoing.size()) };
    if (rv < 0 && errno == EAGAIN) {
        // Socket would block; try again later when POLLOUT arrives
        return;
    }
    
    if (rv < 0) {
        msg_errno("write() error");
        conn->want_close = true;
        return;
    }

    // remove data from 'outgoing'
    buf_consume(conn->outgoing, static_cast<size_t>(rv));

    if (conn->outgoing.size() == 0) { // all data written
        // No more to send; go back to reading next request
        conn->want_read = true;
        conn->want_write = false;
    }
}

// Read available bytes from `conn->fd` into an internal buffer and process complete requests.
// This function performs a single non-blocking read and then repeatedly parses requests
// (via `try_one_request`) until no full request remains.
static void handle_read(Conn *conn) {
    // do a non-blocking read
    uint8_t buf[64 * 1024];
    ssize_t rv { read(conn->fd, buf, sizeof(buf)) };
    if (rv < 0 && errno == EAGAIN) {
        // Nothing to read at the moment
        return;
    }
    
    if (rv < 0) {
        msg_errno("read() error");
        conn->want_close = true;
        return;
    }

    if (rv == 0) {
        // Remote closed connection. If we had partial data treat it as unexpected EOF.
        if (conn->incoming.size() == 0) {
            msg("client closed");
        } else {
            msg("unexpected EOF");
        }
        conn->want_close = true;
        return;
    }

    // add new data to the 'Conn::incoming' buffer
    buf_append(conn->incoming, buf, static_cast<size_t>(rv));

    // parse requests and generate responses
    while (try_one_request(conn)) {}

    // update readiness intention
    if (conn->outgoing.size() > 0) {
        conn->want_read = false;
        conn->want_write = true;

        return handle_write(conn);
    }
}

int main() {
    // Create listening socket
    int fd { socket(AF_INET, SOCK_STREAM, 0) };
    if (fd < 0) {
        die("socket()");
    }

    // Allow quick reuse of address during development
    int val { 1 };
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));

    // bind
    struct sockaddr_in addr { {} };
    addr.sin_family = AF_INET;
    addr.sin_port = ntohs(1234);
    addr.sin_addr.s_addr = ntohl(0);
    int rv { bind(fd, (const struct sockaddr *)&addr, sizeof(addr)) };
    if (rv) {
        die("bind()");
    }

    // set the listen fd to nonblocking mode
    fd_set_nb(fd);

    // listen
    rv = listen(fd, SOMAXCONN);
    if (rv) {
        die("listen()");
    }

    // map of all client connections indexed by their fd
    std::vector<Conn*> fd2conn;

    // event loop
    std::vector<struct pollfd> poll_args;
    while (true) {
        poll_args.clear();

        // put listening socket in first
        struct pollfd pfd { fd, POLLIN, 0 };
        poll_args.push_back(pfd);
        
        // add each active connection to the poll list with the desired events
        for (Conn *conn : fd2conn) {
            if (!conn) continue;

            struct pollfd pfd { conn->fd, POLLERR, 0 };

            if (conn->want_read) {
                pfd.events |= POLLIN;
            }
            if (conn->want_write) {
                pfd.events |= POLLOUT;
            }

            poll_args.push_back(pfd);
        }

        // wait for readiness
        int rv { poll(poll_args.data(), static_cast<nfds_t>(poll_args.size()), -1) };
        if (rv < 0 && errno == EINTR) {
            continue;
        }
        if (rv < 0) {
            die("poll");
        }
            
        // handle the listening socket
        if (poll_args[0].revents) {
            if (Conn *conn {handle_accept(fd)}) {
                if (fd2conn.size() <= static_cast<size_t>(conn->fd)) {
                    fd2conn.resize(conn->fd + 1);
                }
                assert(!fd2conn[conn->fd]);
                fd2conn[conn->fd] = conn;
            }
        }

        // handle connection sockets
        for (size_t i = 1; i < poll_args.size(); ++i) {
            uint32_t ready { poll_args[i].revents };
            Conn *conn { fd2conn[poll_args[i].fd] };

            // handle read or writes
            if (ready & POLLIN) {
                handle_read(conn);
            }
            if (ready & POLLOUT) {
                handle_write(conn);
            }

            // close and cleanup on error or explicit close request
            if ((ready & POLLERR) || (conn->want_close)) {
                static_cast<void>(close(conn->fd));
                fd2conn[conn->fd] = NULL;
                delete conn;
            }
        }
    }

    return 0;
}